tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: product_id
            field:
              type: text
              display: 'Product ID'
              width: 50
              visibility: read_only
          -
            handle: merchant_id
            field:
              type: text
              display: 'Merchant ID'
              width: 50
              visibility: read_only
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
              display: 'Product name'
              visibility: read_only
          -
            handle: product_description
            field:
              type: markdown
              display: 'Product description'
              visibility: read_only
          -
            handle: product_description_ai
            field:
              type: markdown
              display: 'Product description AI'
          -
            handle: product_description_manual
            field:
              type: markdown
              display: 'Product description manual'
          -
            handle: merchant_name
            field:
              type: text
              display: 'Merchant name'
              visibility: read_only
          -
            handle: affiliate_link
            field:
              type: text
              display: 'Affiliate link'
              visibility: read_only
          -
            handle: price
            field:
              type: float
              display: price
              visibility: read_only
              width: 50
          -
            handle: delivery_cost
            field:
              type: float
              display: 'Delivery cost'
              visibility: read_only
              width: 50
          -
            handle: image
            field:
              type: text
              display: Image
              visibility: read_only
          -
            handle: stock
            field:
              type: integer
              display: Stock
              visibility: read_only
          -
            handle: batch_id
            field:
              type: text
              display: batch_id
              visibility: hidden
          -
            handle: feed_name
            field:
              type: text
              display: feed_name
              visibility: read_only
          -
            handle: responsive
            field:
              use_breakpoints: false
              allow_ratio: false
              allow_uploads: false
              type: responsive
              display: responsive
              container: images
          -
            handle: category
            field:
              collections:
                - categories
              type: entries
              display: Category
          -
            handle: merchants
            field:
              max_items: 1
              taxonomies:
                - merchants
              type: terms
              display: Merchants
          -
            handle: regenerate_ai
            field:
              type: toggle
              display: 'Regenerate AI'
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
          -
            handle: parent
            field:
              type: entries
              collections:
                - categories
              max_items: 1
              listable: false
              localizable: true
              visibility: hidden
          -
            handle: belongs_to
            field:
              max_items: 1
              collections:
                - categories
              type: entries
              display: 'Belongs to'
          -
            handle: categories
            field:
              type: terms
              taxonomies:
                - categories
              display: Categorieen
              mode: select
title: Product
